### ISSUE TITLE
slugignore differences

### ISSUE THREAD

**Issue by luislavena** [flynn-archive/slugbuilder#1]
Hello,

When looking at the builder script and compared it to Heroku documentation, I noticed that there are some differences.

Heroku states:

> The `.slugignore` file causes files to be removed after you push code to Heroku and before the buildpack runs.

However, in the script, it is only considered during `tar` of the archive:

https://github.com/flynn/slugbuilder/blob/master/builder/build.sh#L103

I'm wondering if tar exclude rules can properly support absolute slugignore rules like `/spec`.

This is more just a question than an Issue.

Thank you for your time and your work on this!

**Comment by progrium** [comment]
You're right, the ignore happens after buildpack runs instead of before.
However, until that presents an issue I think we'll leave it since it's
simpler to include it in the tar operation we need to do there anyway.

As far as absolute ignores, I'm not sure ... it's run from the root of your
app, which is /app ... and if you wanted /app/spec, then the ignore rule
you want would just be `spec`. If you wanted actual absolute ignores (like
/tmp or /usr/something), that wouldn't have any effect because it's not
even touching that part of the filesystem. So in short, I don't think
absolute ignores are supported, nor would they be useful anyway... does
that help?

On Mon, Oct 21, 2013 at 6:34 AM, Luis Lavena notifications@github.comwrote:

> Hello,
> 
> When looking at the builder script and compared it to Heroku
> documentation, I noticed that there are some differences.
> 
> Heroku states:
> 
> The .slugignore file causes files to be removed after you push code to
> Heroku and before the buildpack runs.
> 
> However, in the script, it is only considered during tar of the archive:
> 
> https://github.com/flynn/slugbuilder/blob/master/builder/build.sh#L103
> 
> I'm wondering if tar exclude rules can properly support absolute
> slugignore rules like /spec.
> 
> This is more just a question than an Issue.
> 
> Thank you for your time and your work on this!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugbuilder/issues/1
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
Oh, but I see Heroku's slugignore and gitignore support patterns that start with / ... I didn't realize that would work. In that case, I'm not sure, but it wouldn't be that hard to try it.

**Comment by luislavena** [comment]
@progrium yeah, I was talking about those patterns in slugignore and gitignore, as indicated in Heroku's devcenter.

Going to try this later tonight and see if this affects (ala: works) or not.

Thank you.

**Comment by luislavena** [comment]
Ok, tar excludes will actually _not work_ with slugignore that contains slashes (`/spec` or `/fixtures`)

This is what I get on Heroku:

```
$ git push heroku master
...

-----> Deleting 1 files matching .slugignore patterns.
-----> Ruby/Rack app detected
```

The `.slugignore` file looks like this:

```
/spec
```

When tried the same with slugbuilder, the `/spec` directory was included in the slug:

```
$ tar -tvf example-ruby-sinatra-v2.tgz | grep spec
...
drwxrwxr-x root/root         0 2013-10-21 23:36 ./spec/
-rw-rw-r-- root/root         0 2013-10-21 23:36 ./spec/garbage.rb
```

This means that slugignore is not 100% compatible and could result in bigger slug sizes.

**Comment by luislavena** [comment]
Looking a bit around seems Heroku is moving from the old slug compiler to a Ruby-based one:

https://github.com/heroku/slug-compiler

Still not in production, but it seems that slugignore is a bit more complicated than just excluding from tarball:

https://github.com/heroku/slug-compiler/blob/master/lib/slug_compiler.rb#L121

**Comment by progrium** [comment]
It would probably be a good idea to start using this next-gen compiler in
slugbuilder.

On Mon, Oct 21, 2013 at 5:03 PM, Luis Lavena notifications@github.comwrote:

> Looking a bit around seems Heroku is moving from the old slug compiler to
> a Ruby-based one:
> 
> https://github.com/heroku/slug-compiler
> 
> Still not in production, but it seems that slugignore is a bit more
> complicated than just excluding from tarball:
> 
> https://github.com/heroku/slug-compiler/blob/master/lib/slug_compiler.rb#L121
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugbuilder/issues/1#issuecomment-26767633
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
@luislavena would an easy solution to this be to strip slashes at the beginning of lines?

**Comment by luislavena** [comment]
@progrium wouldn't that exclude anything named in the `.slugignore` file?

**Comment by progrium** [comment]
Hm? I'm saying if there is a `/spec` entry in .slugignore, it would become `spec` and work as usual...

**Comment by luislavena** [comment]
@progrium sorry, I misunderstood your question.

Yes, removal of leading `/` should do the trick :smile:
