### ISSUE TITLE
Conflicting Compression Options

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/slugbuilder#11]
When I attempt to deploy, I'm receiving the error `tar: Conflicting compression options`.  This series of commands illustrates the problem and a potential fix:

```
root@47e670c8b966:/tmp# tar --exclude='.git' --use-compress-program=pigz -C  /tmp/build -czf /tmp/slug.tgz . | cat
tar: Conflicting compression options
Try `tar --help' or `tar --usage' for more information.
root@47e670c8b966:/tmp# tar --exclude='.git' --use-compress-program=pigz -C  /tmp/build -cf /tmp/slug.tgz . | cat
root@47e670c8b966:/tmp# ls
build  builder  buildpacks  cache  clustercli.ini  clusterflunk.egg-info  development.ini  hsperfdata_root  manifest.ini  requirements.txt  setup.py  slug.tgz
root@47e670c8b966:/tmp# 
```

I tracked it down to this step of the build process https://github.com/flynn/slugbuilder/blob/master/builder/build.sh#L112.  If the tar operation fails, then the slug won't be built and slugrunner will error out when it attempts to run.  Interestingly enough, this works for me on my vagrant box, but when I attempt to put run it on ubuntu 12.04 on ec2, it fails, even though we're using the flynn/slugbuilder image either way.  Any insight on this?

**Comment by titanous** [comment]
Sounds like you're saying that dropping the `-z` from the tar command will solve the problem? If that's the case, can you submit a PR?

**Comment by jayd3e** [comment]
It solved the problem in an isolated case.  The `-z` flag is for gzip compression no?  Do you know the implications of removing it?  If we can be sure that it's not screwing up some original work that was done on slugbuilder, I can make a PR.

**Comment by titanous** [comment]
I think since we set `--use-compress-program=pigz`, the `-z` is redundant and/or breaks things.

**Comment by jayd3e** [comment]
Ok gotcha, yeah makes sense.  I'll create a pull request for it.
