### ISSUE TITLE
Push shouldn't complete if build fails

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/slugbuilder#13]
Right now if the build fails, the git repo still gets pushed, and the app still gets deployed.  Check this out:

![build fails](http://f.cl.ly/items/2y1t0Y3o0c1l1m270D3f/Screen%20Shot%202014-03-18%20at%2010.47.42%20PM.png)

**Comment by titanous** [comment]
This is a duplicate of flynn/gitreceive-next#5, though I think the bug is actually in flynn-receive.
