### ISSUE TITLE
HHVM

### ISSUE THREAD

**Issue by JosefJezek** [flynn-archive/slugbuilder#17]
Could you add HHVM?

https://github.com/hhvm/heroku-buildpack-hhvm

**Comment by titanous** [comment]
Yep, want to submit a pull request?

**Comment by JosefJezek** [comment]
I don't know dependencies.

**Comment by titanous** [comment]
Buildpacks have no dependencies outside of the cedarish base image. Just add the URL to the list: https://github.com/flynn/slugbuilder/blob/master/builder/buildpacks.txt

**Comment by progrium** [comment]
Pls close
