### ISSUE TITLE
Push image to a private docker repository . 

### ISSUE THREAD

**Issue by enyachoke** [flynn-archive/slugbuilder#3]
I'm just curious about  this

```
if [[ $put_url ]]; then
                curl -0 -s -o /dev/null -X PUT -T $slug_file "$put_url" 
        fi
```

Why not just push to a private docker repo and tag it with an application version or commit then just pull it and create containers with it.

**Comment by titanous** [comment]
@enyachoke slugbuilder isn't intended to be Docker-specific, so we're just using tarballs for slugs instead of tying it to Docker APIs.

**Comment by progrium** [comment]
Also, slugbuilder is about building slug artifacts, not containers.

On Sat, Nov 2, 2013 at 10:03 AM, Jonathan Rudenberg <
notifications@github.com> wrote:

> @enyachoke https://github.com/enyachoke slugbuilder isn't intended to
> be Docker-specific, so we're just using tarballs for slugs instead of tying
> it to Docker APIs.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugbuilder/issues/3#issuecomment-27623657
> .

## 

Jeff Lindsay
http://progrium.com
