### ISSUE TITLE
Generate a  JSON file of process types after build

### ISSUE THREAD

**Issue by enyachoke** [flynn-archive/slugbuilder#4]
On https://github.com/flynn/slugbuilder/blob/master/builder/build.sh#L92 we parse the Procfile and echo the process types. Wont it be a good idea to also generate a json file of the processes to so we can easily save the processes when deploying the app. Something like

``` ruby
require 'json'
require 'yaml'

yml = <<-eos

---
  web: bundle exec rails server -p $PORT
  worker: bundle exec rake jobs:work
  clock: bundle exec clockwork lib/clock.rb
eos

data = YAML::load(yml)
json = JSON.dump(data)

puts json
```

**Comment by progrium** [comment]
But we would still have the Procfile, so you're proposing to just change
it's format from YAML to JSON. I don't see why this is worth doing.

On Sun, Nov 17, 2013 at 8:17 AM, Emmanuel Nyachoke <notifications@github.com

> wrote:
> 
> On https://github.com/flynn/slugbuilder/blob/master/builder/build.sh#L92we parse the Procfile and echo the process types. Wont it be a good idea to
> also generate a json file of the processes to so we can easily save the
> processes when deploying the app. Something like
> 
> require 'json'require 'yaml'
> yml = <<-eos---  web: bundle exec rails server -p $PORT  worker: bundle exec rake jobs:work  clock: bundle exec clockwork lib/clock.rbeos
> data = YAML::load(yml)json = JSON.dump(data)
> puts json
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/slugbuilder/issues/4
> .

## 

Jeff Lindsay
http://progrium.com
